/*
 * This source file was generated by the Gradle 'init' task
 */
package catergoo;

public class CatergooApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new CatergooApp().getGreeting());
    }
}
